version: "3.9"
services:
  edgeapi:
    container_name: EdgeApiApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8086:8086
    networks:
      - warehouse_common_network
  #keycloak:
  #  container_name: keycloak_edgeapi
  #  image: quay.io/keycloak/keycloak:19.0.1
  #  volumes:
  #    - ./realm:/opt/keycloak/data/import
  #  environment:
  #    KEYCLOAK_ADMIN: admin
  #    KEYCLOAK_ADMIN_PASSWORD: admin
  #  command:
  #    - start-dev
  #    - --import-realm
  #  restart: always
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - warehouse_common_network
networks:
  warehouse_common_network:
    external: true
