spring:
  application:
    name: edge-api
keycloak:
  realm: KBERTV
  auth-server-url: http://keycloak:8080
  resource: kbertv-backend
  bearer-only: true
  credentials:
    secret: J56ggduDVYz2rtS6dsM05bpAdpxLCx7Y
server:
  port: 8086
