spring:
  application:
    name: edge-api
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: warehousecomponents
          uri: http://warehouse:8081/
          predicates:
            - Path=/components/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/KBERTV
            # Individual properties can also be provided this way
            #token-uri: http://keycloak:8080/realms/KBE-Realm/protocol/openid-connect/token
            #authorization-uri: http://keycloak:8080/realms/KBE-Realm/protocol/openid-connect/auth
            #user-info-uri: http://keycloak:8080/realms/KBE-Realm/protocol/openid-connect/userinfo
        registration:
          kbertv:
            provider: keycloak-provider
            client-id: kbertv
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/login/oauth2/code/kbertv
            scope:
              - openid
server:
  port: 8086