spring:
  application:
    name: edge-api
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: warehousecomponents
          uri: http://localhost:8081
          predicates:
            - Path=/components/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/KBE-Realm
            # Individual properties can also be provided this way
            #token-uri: http://localhost:8080/realms/KBE-Realm/protocol/openid-connect/token
            #authorization-uri: http://localhost:8080/realms/KBE-Realm/protocol/openid-connect/auth
            #user-info-uri: http://localhost:8080/realms/KBE-Realm/protocol/openid-connect/userinfo
        registration:
          edge-gateway-client:
            provider: keycloak-provider
            client-id: edge-gateway-client
            client-secret: 6Y0GYrQUC8HgNv5Rh7hPsVisewlX7Qq5
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8086/login/oauth2/code/edge-gateway-client"
server:
  port: 8086